// SRW
#include "config.h"

#if !defined(BOARD_SPUDGLO_MINI_V1_GPIO_CONFIG_H)
#define BOARD_SPUDGLO_MINI_V1_GPIO_CONFIG_H
#include "gpio_config_hal.h"


typedef enum
{
	// mapping of specific GPIO to the GPIO defined in gpio_config_hal.h
	GPIO_PIN_NC1				= GPIO_PIOA_PIN_0,
	GPIO_PIN_NC2				= GPIO_PIOA_PIN_1,
	GPIO_PIN_NC3				= GPIO_PIOA_PIN_2,
	GPIO_PIN_NC4				= GPIO_PIOA_PIN_3,
	GPIO_PIN_NC5				= GPIO_PIOA_PIN_4,
	GPIO_PIN_NC6				= GPIO_PIOA_PIN_5,
	GPIO_PIN_NC7				= GPIO_PIOA_PIN_6,
	GPIO_PIN_NC8				= GPIO_PIOA_PIN_7,
	GPIO_PIN_TIM1_CH1		    = GPIO_PIOA_PIN_8,
	GPIO_PIN_NC9			    = GPIO_PIOA_PIN_9,
	GPIO_PIN_NC11				= GPIO_PIOA_PIN_10,
	GPIO_PIN_NC12				= GPIO_PIOA_PIN_11,
	GPIO_PIN_NC13				= GPIO_PIOA_PIN_12,
	GPIO_PIN_SWDIO				= GPIO_PIOA_PIN_13,
	GPIO_PIN_SWCLK				= GPIO_PIOA_PIN_14,
	GPIO_PIN_NC14				= GPIO_PIOA_PIN_15,

	GPIO_PIN_NC15				= GPIO_PIOB_PIN_0,
	GPIO_PIN_NC16				= GPIO_PIOB_PIN_1,
	GPIO_PIN_NC17				= GPIO_PIOB_PIN_2,
	GPIO_PIN_NC18				= GPIO_PIOB_PIN_3,
	GPIO_PIN_NC19				= GPIO_PIOB_PIN_4,
	GPIO_PIN_NC20				= GPIO_PIOB_PIN_5,
	GPIO_PIN_NC21				= GPIO_PIOB_PIN_6,
	GPIO_PIN_NC22				= GPIO_PIOB_PIN_7,
	GPIO_PIN_NC23				= GPIO_PIOB_PIN_8,
	GPIO_PIN_NC24				= GPIO_PIOB_PIN_9,
	GPIO_PIN_NC25				= GPIO_PIOB_PIN_10,
	GPIO_PIN_NC26				= GPIO_PIOB_PIN_11,
	GPIO_PIN_NC27				= GPIO_PIOB_PIN_12,
	GPIO_PIN_NC28				= GPIO_PIOB_PIN_13,
	GPIO_PIN_NC29				= GPIO_PIOB_PIN_14,
	GPIO_PIN_NC30				= GPIO_PIOB_PIN_15,

	GPIO_PIN_XR_TX 				= GPIO_PIOC_PIN_0,
	GPIO_PIN_XR_RX 				= GPIO_PIOC_PIN_1,
	GPIO_PIN_NC31 				= GPIO_PIOC_PIN_2,
	GPIO_PIN_NC32 				= GPIO_PIOC_PIN_3,
	GPIO_PIN_NC33				= GPIO_PIOC_PIN_4,
	GPIO_PIN_NC34				= GPIO_PIOC_PIN_5,
	GPIO_PIN_NC35				= GPIO_PIOC_PIN_6,
	GPIO_PIN_NC36				= GPIO_PIOC_PIN_7,
	GPIO_PIN_NC37				= GPIO_PIOC_PIN_8,
	GPIO_PIN_NC38				= GPIO_PIOC_PIN_9,
	GPIO_PIN_NC39				= GPIO_PIOC_PIN_10,
	GPIO_PIN_NC40				= GPIO_PIOC_PIN_11,
	GPIO_PIN_NC41				= GPIO_PIOC_PIN_12,
	GPIO_PIN_NC42				= GPIO_PIOC_PIN_13,
	GPIO_PIN_NC43				= GPIO_PIOC_PIN_14,
	GPIO_PIN_NC44				= GPIO_PIOC_PIN_15,

	GPIO_PIN_NC45				= GPIO_PIOD_PIN_2,

	GPIO_PIN_OSC48_HI			= GPIO_PIOH_PIN_0,
	GPIO_PIN_OSC48_LO			= GPIO_PIOH_PIN_1,
	GPIO_PIN_BOOT0				= GPIO_PIOH_PIN_3

} gpio_specific_pin_e;

#endif // BOARD_SPUDGLO_BABY_DINOSAUR_V1_GPIO_CONFIG_H

