// SRW
#include "config.h"

#if !defined(BOARD_SPUDGLO_V9_GPIO_CONFIG_H) && defined(BOARD_SPUDGLO_V9)
#define BOARD_SPUDGLO_V9_GPIO_CONFIG_H
#include "gpio_config_hal.h"


typedef enum
{
	// mapping of specific GPIO to the GPIO defined in gpio_config_hal.h
	GPIO_PIN_XR_TX 				= GPIO_PIOC_PIN_0,
	GPIO_PIN_XR_RX 				= GPIO_PIOC_PIN_1,
	// PIOC2, 3, 4
	GPIO_PIN_WKUP3 				= GPIO_PIOC_PIN_5,
	GPIO_PIN_PUSH_BUTTON_A		= GPIO_PIN_WKUP3,
	// PIOC6
	GPIO_PIN_LVL_DIR 			= GPIO_PIOC_PIN_7,
	GPIO_PIN_LVL_EN 			= GPIO_PIOC_PIN_8,
	// PIOC9, 10, 11, 12
	GPIO_PIN_WKUP2 				= GPIO_PIOC_PIN_13,
	GPIO_PIN_PUSH_BUTTON_B 		= GPIO_PIN_WKUP2,
	// PIOC14, 15
	GPIO_PIN_WKUP1				= GPIO_PIOA_PIN_0,
	GPIO_PIN_PUSH_BUTTON_C 		= GPIO_PIN_WKUP1,
	// PIOA1
	GPIO_PIN_WKUP4				= GPIO_PIOA_PIN_2,
	GPIO_PIN_PUSH_BUTTON_D 		= GPIO_PIN_WKUP4,
	// PIOA3, 4, 5, 6, 7
	GPIO_PIN_TIM1_CH1			= GPIO_PIOA_PIN_8,
	GPIO_PIN_TIM1_CH2			= GPIO_PIOA_PIN_9,
	GPIO_PIN_TIM1_CH3			= GPIO_PIOA_PIN_10,
	// PIOA11, 12
	// PIOA13, 14, 15 PROGRAMMING SIGNALS
	// PIOB0
	GPIO_PIN_RV_8803_INT_N		= GPIO_PIOB_PIN_1,
	// PIOB2
	// PIOB3, 4 PROGRAMMING SIGNALS
	// PIOB5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
	// PH0,1
	// PH3
	// PD2
} gpio_specific_pin_e;

#endif

