// SRW

#include "numbers.h"
#include "ws2812b.h"
#include "FreeRTOS.h"
#include "portmacro.h"
#include "led_state.h"
#include "led_ctrl_speed.h"
#include "led_ctrl_interrupt.h"
#include "led_ctrl_time.h"
#include "free_rtos_convenience.h"
#include "led_ctrl.h"

const uint16_t g_led_ctrl_time_delay_inner_loop[NUM_LED_STATES][NUM_LED_SPEEDS] =
{
	[LED_STATE_SPELL][LED_SPEED_1000P] 						= 2,
	[LED_STATE_SPELL][LED_SPEED_500P] 						= 20,
	[LED_STATE_SPELL][LED_SPEED_100P] 						= 66,
	[LED_STATE_SPELL][LED_SPEED_50P] 						= 132,
	[LED_STATE_SPELL][LED_SPEED_25P] 						= 250,

	[LED_STATE_WHITE_COLOR][LED_SPEED_1000P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_500P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_100P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_50P] 					= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_25P] 					= 10000,

	[LED_STATE_SOLID_COLOR][LED_SPEED_1000P]	 			= 5000,
	[LED_STATE_SOLID_COLOR][LED_SPEED_500P] 				= 5000,
	[LED_STATE_SOLID_COLOR][LED_SPEED_100P] 				= 5000,
	[LED_STATE_SOLID_COLOR][LED_SPEED_50P] 					= 5000,
	[LED_STATE_SOLID_COLOR][LED_SPEED_25P] 					= 5000,

	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_1000P] 			= 2,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_500P] 			= 20,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_100P] 			= 150,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_50P] 				= 132,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_25P] 				= 250,

	[LED_STATE_SPARKLE_FILL][LED_SPEED_1000P] 				= 2,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_500P] 				= 20,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_100P] 				= 66,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_50P] 				= 132,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_25P] 				= 250,

	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_1000P] 				= 2,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_500P] 				= 15,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_100P] 				= 30,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_50P] 				= 60,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_25P] 				= 125,

	[LED_STATE_THEATER_CHASE][LED_SPEED_1000P] 				= 2,
	[LED_STATE_THEATER_CHASE][LED_SPEED_500P] 				= 45,
	[LED_STATE_THEATER_CHASE][LED_SPEED_100P] 				= 66,
	[LED_STATE_THEATER_CHASE][LED_SPEED_50P] 				= 132,
	[LED_STATE_THEATER_CHASE][LED_SPEED_25P] 				= 250,

	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_1000P] 		= 2,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_500P] 		= 45,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_100P] 		= 66,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_50P] 		= 132,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_25P] 		= 250,

	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_1000P]		 	= 2,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_500P] 			= 20,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_100P] 			= 45,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_50P] 				= 80,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_25P] 				= 120,
};


const uint16_t g_led_ctrl_time_delay_outer_loop[NUM_LED_STATES][NUM_LED_SPEEDS] =
{
	[LED_STATE_SPELL][LED_SPEED_1000P] 						= 0,
	[LED_STATE_SPELL][LED_SPEED_500P] 						= 0,
	[LED_STATE_SPELL][LED_SPEED_100P] 						= 0,
	[LED_STATE_SPELL][LED_SPEED_50P] 						= 0,
	[LED_STATE_SPELL][LED_SPEED_25P] 						= 0,

	[LED_STATE_WHITE_COLOR][LED_SPEED_1000P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_500P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_100P] 				= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_50P] 					= 10000,
	[LED_STATE_WHITE_COLOR][LED_SPEED_25P] 					= 10000,

	[LED_STATE_SOLID_COLOR][LED_SPEED_1000P]	 			= 7500,
	[LED_STATE_SOLID_COLOR][LED_SPEED_500P] 				= 7500,
	[LED_STATE_SOLID_COLOR][LED_SPEED_100P] 				= 7500,
	[LED_STATE_SOLID_COLOR][LED_SPEED_50P] 					= 7500,
	[LED_STATE_SOLID_COLOR][LED_SPEED_25P] 					= 7500,

	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_1000P] 			= 0,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_500P] 			= 0,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_100P] 			= 0,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_50P] 				= 0,
	[LED_STATE_SPARKLE_NO_FILL][LED_SPEED_25P] 				= 0,

	[LED_STATE_SPARKLE_FILL][LED_SPEED_1000P] 				= 0,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_500P] 				= 0,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_100P] 				= 0,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_50P] 				= 0,
	[LED_STATE_SPARKLE_FILL][LED_SPEED_25P] 				= 0,

	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_1000P] 				= 0,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_500P] 				= 0,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_100P] 				= 0,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_50P] 				= 0,
	[LED_STATE_RAINBOW_CYCLE][LED_SPEED_25P] 				= 0,

	[LED_STATE_THEATER_CHASE][LED_SPEED_1000P] 				= 0,
	[LED_STATE_THEATER_CHASE][LED_SPEED_500P] 				= 0,
	[LED_STATE_THEATER_CHASE][LED_SPEED_100P] 				= 0,
	[LED_STATE_THEATER_CHASE][LED_SPEED_50P] 				= 0,
	[LED_STATE_THEATER_CHASE][LED_SPEED_25P] 				= 0,

	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_1000P] 		= 0,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_500P] 		= 0,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_100P] 		= 0,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_50P] 		= 0,
	[LED_STATE_THEATER_CHASE_RAINBOW][LED_SPEED_25P] 		= 0,

	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_1000P]		 	= 0,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_500P] 			= 0,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_100P] 			= 0,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_50P] 				= 0,
	[LED_STATE_FADE_IN_AND_OUT][LED_SPEED_25P] 				= 0,

};


/**
 * @brief   Function to delay an amount of time.
 * @param   mask - enabled strips to check if button press effects.
 * @param   time_ms - time to delay
 * @return  bool - true if interrupt occured else false.
 * @note    If interrupt occured then the function may not delay the full
 *          amount of time.
 */
bool led_ctrl_time_delay(const strip_mask_t mask, const uint32_t time_ms)
{
    uint32_t ms_count = 0;
    uint32_t ticks = 0;

    if (!time_ms) return false;

    ticks = time_ms / portTICK_PERIOD_MS;

    while (ms_count++ < ticks)
    {
        taskYIELD();
        free_rtos_delay_ms(portTICK_PERIOD_MS);
        if (led_ctrl_interrupt_major_or_minor_flag_set(mask)) return true;
    }
    return false;
}
