// SRW

#include "config.h"
#if !defined(BOARD_INIT_SPUDGLO_BABY_DINOSAUR_V1_TIMER_CONFIG_H)
#define BOARD_INIT_SPUDGLO_BABY_DINOSAUR_V1_TIMER_CONFIG_H

typedef enum
{
	TIMER_ACCESS_TIMER_INSTANCE_1_FIRST,
	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_1 = TIMER_ACCESS_TIMER_INSTANCE_1_FIRST,
//	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_2,
//	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_3,
	NUM_TIMER_ACCESS_TIMER_INSTANCES
} timer_access_timer_instances_e;
//
//typedef enum
//{
//	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_FIRST,
//	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_1,
////	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_2,
////	TIMER_ACCESS_TIMER_INSTANCE_1_CHANNEL_3,
//	NUM_TIMER_ACCESS_TIMER_INSTANCES
//} timer_access_timer_instances_e;



#endif
