/***********************************
 * @file   color_led.h
 * @author SpudGlo LLC
 ***********************************/
#if !defined(LED_COLOR_H)
#define LED_COLOR_H
//#include <limits.h>
#include "ws2812b.h"
#include "button_access.h"

typedef enum
{
    LED_COLOR_MASTER_STATE_DEMO,
    LED_COLOR_MASTER_STATE_FIXED
} led_color_master_state_e;

typedef enum
{
    LED_COLOR_FIRST             = 0,
    LED_COLOR_BLACK             = LED_COLOR_FIRST,
    LED_COLOR_WHITE,
    LED_COLOR_RED,
    LED_COLOR_LIME,
    LED_COLOR_BLUE,
    LED_COLOR_YELLOW,
    LED_COLOR_CYAN,
    LED_COLOR_MAGENTA,
    LED_COLOR_SILVER,
    LED_COLOR_GRAY,
    LED_COLOR_DARK_GRAY,
    LED_COLOR_CHARCOAL,
    LED_COLOR_MAROON,
    LED_COLOR_OLIVE,
    LED_COLOR_GREEN,
    LED_COLOR_PURPLE,
    LED_COLOR_TEAL,
    LED_COLOR_NAVY,
    LED_COLOR_ORANGE_RED,
    LED_COLOR_ORANGE,
    LED_COLOR_KHAKI,
    LED_COLOR_LAWN_GREEN,
    LED_COLOR_SPRING_GREEN,
    LED_COLOR_MIDNIGHT_BLUE,
    LED_COLOR_BLUE_VIOLET,
    LED_COLOR_DARK_MAGENTA,
    LED_COLOR_HOT_PINK,
    LED_COLOR_MINT,
    LED_COLOR_TAN,
    LED_COLOR_BROWN,
    LED_COLOR_RED_BROWN,
    LED_COLOR_SADDLE_BROWN,
    LED_COLOR_CHOCOLATE,
    LED_COLOR_ROSY_BROWN,
    LED_COLOR_DARK_TAN,
    LED_COLOR_DARK_RED,
    LED_COLOR_SALMON,
    LED_COLOR_GOLD,
    LED_COLOR_FOREST_GREEN,
    LED_COLOR_AQUA_MARINE,
    LED_COLOR_DARK_BLUE,
    LED_COLOR_VIOLET,
    LED_COLOR_INDIGO,
    LED_COLOR_PLUM,
    LED_COLOR_PINK,
    LED_COLOR_DEEP_PINK,

    LED_COLOR_LAST             = LED_COLOR_DEEP_PINK,
    NUM_COLORS,
    LED_COLOR_NONE
} led_color_e;


// complete list of all hex color codes
typedef enum
{
    // RGB
    LED_COLOR_HEX_BLACK         = 0x000000,
    LED_COLOR_HEX_WHITE         = 0xFFFFFF,
    LED_COLOR_HEX_RED           = 0xFF0000,
    LED_COLOR_HEX_LIME          = 0x00FF00,
    LED_COLOR_HEX_BLUE          = 0x0000FF,
    LED_COLOR_HEX_YELLOW        = 0xFFFF00,
    LED_COLOR_HEX_CYAN          = 0x00FFFF,
    LED_COLOR_HEX_MAGENTA       = 0xFF00FF,
    LED_COLOR_HEX_SILVER        = 0xC0C0C0,
    LED_COLOR_HEX_GRAY          = 0x808080,
	LED_COLOR_HEX_DARK_GRAY 	= 0xA9A9A9,
	LED_COLOR_HEX_CHARCOAL		= 0x36454F,
    LED_COLOR_HEX_MAROON        = 0x800000,
    LED_COLOR_HEX_OLIVE         = 0x808000,
    LED_COLOR_HEX_GREEN         = 0x008000,
    LED_COLOR_HEX_PURPLE        = 0x800080,
    LED_COLOR_HEX_TEAL          = 0x008080,
    LED_COLOR_HEX_NAVY          = 0x000080,
    LED_COLOR_HEX_ORANGE_RED    = 0xFF4500,
    LED_COLOR_HEX_ORANGE        = 0xFFA500,
    LED_COLOR_HEX_KHAKI         = 0xF0E68C,
    LED_COLOR_HEX_LAWN_GREEN    = 0x7CFC00,
    LED_COLOR_HEX_SPRING_GREEN  = 0x00FF7F,
    LED_COLOR_HEX_MIDNIGHT_BLUE = 0x191970,
    LED_COLOR_HEX_BLUE_VIOLET   = 0x8A2BE2,
    LED_COLOR_HEX_DARK_MAGENTA  = 0x8B008B,
    LED_COLOR_HEX_HOT_PINK      = 0xFF69B4,
    LED_COLOR_HEX_MINT          = 0x4EBD88,
	LED_COLOR_HEX_TAN			= 0xD2B48C,
    LED_COLOR_HEX_BROWN         = 0xA52A2A,
	LED_COLOR_HEX_RED_BROWN		= 0x7F2B0A,
	LED_COLOR_HEX_SADDLE_BROWN	= 0x8B4513,
	LED_COLOR_HEX_CHOCOLATE		= 0xD2691E,
	LED_COLOR_HEX_ROSY_BROWN	= 0xBC8F8F,
	LED_COLOR_HEX_DARK_TAN		= 0x988558,
	LED_COLOR_HEX_DARK_RED		= 0x8B0000,
	LED_COLOR_HEX_SALMON		= 0xFA8072,
	LED_COLOR_HEX_GOLD			= 0xFFD700,
	LED_COLOR_HEX_FOREST_GREEN	= 0x228B22,
	LED_COLOR_HEX_AQUA_MARINE 	= 0x7FFFD4,
	LED_COLOR_HEX_DARK_BLUE		= 0x00008B,
	LED_COLOR_HEX_VIOLET		= 0x7F00FF,
	LED_COLOR_HEX_INDIGO 		= 0x4B0082,
	LED_COLOR_HEX_PLUM			= 0x8E4585,
	LED_COLOR_HEX_PINK			= 0xFFC0CB,
	LED_COLOR_HEX_DEEP_PINK		= 0xE75480,
	LED_COLOR_HEX_LAST_VALUE	= LED_COLOR_HEX_WHITE,
} led_color_hex_code_e;


typedef struct
{
    led_color_e                 led_color;
    union
    {
        led_color_hex_code_e    led_color_hex_code;
        struct
        {
            ws2812b_led_t       color_rgb;
            uint8_t             rsvd;
        };
    };
} led_color_t;


typedef enum
{
    LED_COLOR_MAJOR_STATE_CHANGE_SPEED      = LED_COLOR_HEX_GREEN,
    LED_COLOR_MAJOR_STATE_CHANGE_STATE      = LED_COLOR_HEX_BLUE,
    LED_COLOR_MAJOR_STATE_CHANGE_COLOR      = LED_COLOR_HEX_RED,
    LED_COLOR_MAJOR_STATE_CHANGE_BRIGHTNESS = LED_COLOR_HEX_WHITE
} led_color_major_state_change_e;

led_color_hex_code_e led_color_enum_to_hex_code(led_color_e led_color);
led_color_e led_color_hex_to_enum(led_color_hex_code_e led_color_hex);
#endif
