// SRW
#include "config.h"

#if !defined(BOARD_SPUDGLO_V5_GPIO_CONFIG_H)
#define BOARD_SPUDGLO_V5_GPIO_CONFIG_H
#if defined(BOARD_SPUDGLO_V5P0)
#include "gpio_config_hal.h"


typedef enum
{
	// mapping of specific GPIO to the GPIO defined in gpio_config_hal.h
	GPIO_PIN_XR_TX 				= GPIO_PIOC_PIN_0,
	GPIO_PIN_XR_RX 				= GPIO_PIOC_PIN_1,
	GPIO_PIN_GREEN_LED 			= GPIO_PIOC_PIN_2,
	GPIO_PIN_RED_LED 			= GPIO_PIOC_PIN_3,
	// PIOC4
	GPIO_PIN_WKUP3 				= GPIO_PIOC_PIN_5,
	GPIO_PIN_PUSH_BUTTON_A		= GPIO_PIN_WKUP3,
	// PIOC6
	GPIO_PIN_LVL_EN 			= GPIO_PIOC_PIN_7,
	GPIO_PIN_LVL_DIR 			= GPIO_PIOC_PIN_8,
	// PIOC9,10,11,12
	GPIO_PIN_WKUP2 				= GPIO_PIOC_PIN_13,
	GPIO_PIN_PUSH_BUTTON_B 		= GPIO_PIN_WKUP2,
	// PIOC14,15
	GPIO_PIN_WKUP1				= GPIO_PIOA_PIN_0,
	GPIO_PIN_PUSH_BUTTON_C 		= GPIO_PIN_WKUP1,
	GPIO_PIN_ESP8266_SCK		= GPIO_PIOA_PIN_1,
	GPIO_PIN_WKUP4				= GPIO_PIOA_PIN_2,
	GPIO_PIN_PUSH_BUTTON_D 		= GPIO_PIN_WKUP4,
	// PIOA3
	GPIO_PIN_ESP8266_CSN		= GPIO_PIOA_PIN_4,
	GPIO_PIN_ESP8266_GPIO0		= GPIO_PIOA_PIN_5,
	GPIO_PIN_ESP8266_EN			= GPIO_PIOA_PIN_6,
	GPIO_PIN_ESP8266_RST		= GPIO_PIOA_PIN_7,
	GPIO_PIN_TIM1_CH1			= GPIO_PIOA_PIN_8,
	GPIO_PIN_TIM1_CH2			= GPIO_PIOA_PIN_9,
	GPIO_PIN_TIM1_CH3			= GPIO_PIOA_PIN_10,
	GPIO_PIN_ESP8266_MISO		= GPIO_PIOA_PIN_11,
	GPIO_PIN_ESP8266_MOSI		= GPIO_PIOA_PIN_12,
	//PIOA13,14,15 PROGRAMMING SIGNALS
	//PIOB0,1,2
	//PIOB3,4 PROGRAMMING SIGNALS
	//PIOB5
	GPIO_PIN_ESP8266_RXD		= GPIO_PIOB_PIN_6,
	GPIO_PIN_ESP8266_TXD		= GPIO_PIOB_PIN_7,
	//PIOB8,9,10,11
	GPIO_PIN_XR_GPIO			= GPIO_PIOB_PIN_12,
	GPIO_PIN_VBUS_PRESENT		= GPIO_PIOB_PIN_13

} gpio_specific_pin_e;

#endif
#endif

