// SRW
#include "config.h"
#if !defined(BOARD_SPUDGLO_BUSINESS_CARD_GPIO_CONFIG_H) && defined(BOARD_SPUDGLO_BUSINESS_CARD)
#define BOARD_SPUDGLO_BUSINESS_CARD_GPIO_CONFIG_H
#include "gpio_config_hal.h"





typedef enum
{
	// mapping of specific GPIO to the GPIO defined in gpio_config_hal.h
	GPIO_PIN_VBAT_MON 			= GPIO_PIOC_PIN_0,
	//PIOC1,2,3,4
	GPIO_PIN_WKUP3 				= GPIO_PIOC_PIN_5, // COLOR
	GPIO_PIN_PUSH_BUTTON_A		= GPIO_PIN_WKUP3,
	// PIOC6
	GPIO_PIN_LVL_EN 			= GPIO_PIOC_PIN_7,
	GPIO_PIN_LVL_DIR 			= GPIO_PIOC_PIN_8,
	// PIOC9,10,11,12
	GPIO_PIN_WKUP2 				= GPIO_PIOC_PIN_13, // ANIMATION
	GPIO_PIN_PUSH_BUTTON_B 		= GPIO_PIN_WKUP2,
	// PIOC14,15
	GPIO_PIN_WKUP1				= GPIO_PIOA_PIN_0, // SPEED
	GPIO_PIN_PUSH_BUTTON_C 		= GPIO_PIN_WKUP1,
	// PIOA1
	GPIO_PIN_WKUP4				= GPIO_PIOA_PIN_2, // PAUSE
	GPIO_PIN_PUSH_BUTTON_D 		= GPIO_PIN_WKUP4,
	// PIOA3,4,5,6
	GPIO_PIN_RED_LED			= GPIO_PIOA_PIN_7,
	GPIO_PIN_TIM1_CH1			= GPIO_PIOA_PIN_8,
	// PIOA9,10,11,12
	//PIOA13,14,15 PROGRAMMING SIGNALS
	//PIOB0,1,2
	//PIOB3,4 PROGRAMMING SIGNALS
	//PIOB5,6,7,8,9,10,11,12,13,14,15

} gpio_specific_pin_e;

#endif

