// SRW
#include "config.h"

#if !defined(BOARD_SPUDGLO_V8_GPIO_CONFIG_H) && defined(BOARD_SPUDGLO_V8)
#define BOARD_SPUDGLO_V8_GPIO_CONFIG_H
#include "gpio_config_hal.h"


typedef enum
{
	// mapping of specific GPIO to the GPIO defined in gpio_config_hal.h
	GPIO_PIN_XR_TX 				= GPIO_PIOC_PIN_0,
	GPIO_PIN_XR_RX 				= GPIO_PIOC_PIN_1,
	GPIO_PIN_V_BUTTON 			= GPIO_PIOC_PIN_2,
	// PIOC3,4
	GPIO_PIN_WKUP3 				= GPIO_PIOC_PIN_5,
	GPIO_PIN_PUSH_BUTTON_A		= GPIO_PIN_WKUP3,
	// PIOC6
	GPIO_PIN_LVL_EN 			= GPIO_PIOC_PIN_7,
	GPIO_PIN_LVL_DIR 			= GPIO_PIOC_PIN_8,
	// PIOC9,10,11,12
	GPIO_PIN_WKUP2 				= GPIO_PIOC_PIN_13,
	GPIO_PIN_PUSH_BUTTON_B 		= GPIO_PIN_WKUP2,
	GPIO_PIN_RV_8803_CLK_OUT    = GPIO_PINC_PIN_14,
	// PIOC15
	GPIO_PIN_WKUP1				= GPIO_PIOA_PIN_0,
	GPIO_PIN_PUSH_BUTTON_C 		= GPIO_PIN_WKUP1,
	GPIO_PIN_RV_8803_CLK_EN		= GPIO_PIOA_PIN_1,
	GPIO_PIN_WKUP4				= GPIO_PIOA_PIN_2,
	GPIO_PIN_PUSH_BUTTON_D 		= GPIO_PIN_WKUP4,
	// PIOA3,4,5
	GPIO_PIN_XR_GPIO			= GPIO_PIOA_PIN_6,
	GPIO_PIN_VBUS_PRESENT		= GPIO_PIOA_PIN_7,
	GPIO_PIN_TIM1_CH1			= GPIO_PIOA_PIN_8,
	GPIO_PIN_TIM1_CH2			= GPIO_PIOA_PIN_9,
	GPIO_PIN_TIM1_CH3			= GPIO_PIOA_PIN_10,
    // PIOA11,12
	//PIOA13,14,15 PROGRAMMING SIGNALS
	//PIOB0
	GPIO_PIN_RV_8803_INT_N		= GPIO_PIOB_PIN_1,
	//PIOB2
	//PIOB3,4 PROGRAMMING SIGNALS
	//PIOB5,6,7,8,9
	GPIO_PIN_I2C2_SCL   		= GPIO_PIOB_PIN_10,
	GPIO_PIN_I2C2_SDA   		= GPIO_PIOB_PIN_11,
	GPIO_PIN_GPIO_4			    = GPIO_PIOB_PIN_12,
    GPIO_PIN_GPIO_3             = GPIO_PIOB_PIN_13,
    GPIO_PIN_GPIO_2             = GPIO_PIOB_PIN_14,
    GPIO_PIN_GPIO_1             = GPIO_PIOB_PIN_15,
    // PH0,1
    // PH3
    // PD2
} gpio_specific_pin_e;

#endif

